# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd" "nct6775" "k10temp"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e9a76adc-b1c8-46f2-9866-e7116536752d";
    fsType = "btrfs";
    options = ["subvol=root" "compress=zstd" "noatime"];
  };

  fileSystems."/flake" = {
    device = "/dev/disk/by-uuid/e9a76adc-b1c8-46f2-9866-e7116536752d";
    fsType = "btrfs";
    options = ["subvol=flake" "compress=zstd" "noatime"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/e9a76adc-b1c8-46f2-9866-e7116536752d";
    fsType = "btrfs";
    options = ["subvol=home" "compress=zstd" "noatime"];
  };

  fileSystems."/games" = {
    device = "/dev/disk/by-uuid/0e703968-ca59-4e3d-bbea-16aab36412cc";
    fsType = "btrfs";
    options = ["subvol=games" "compress=zstd" "noatime" "nofail"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/e9a76adc-b1c8-46f2-9866-e7116536752d";
    fsType = "btrfs";
    options = ["subvol=nix" "compress=zstd" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7A6A-6F00";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
