{
  config,
  lib,
  pkgs,
  nixosConfig ? {},
  ...
}: let
  cfg = config.dotfiles.services.music.mpdscribble;
  xdgState = config.xdg.state.directory;
  xdgConfig = config.xdg.config.directory;
  mpdOn = config.dotfiles.services.music.mpd.enable;
  servicesOn = nixosConfig.dotfiles.services.enable;

  defaultUrls = {
    "last.fm" = "http://post.audioscrobbler.com";
    "libre.fm" = "http://turtle.libre.fm";
    "jamendo" = "http://postaudioscrobbler.jamendo.com";
    "listenbrainz" = "http://proxy.listenbrainz.org";
  };

  mkTemplate = ''
    ## Generated by hjem – do not edit directly

    log = -
    verbose = ${toString cfg.verbose}
    journal_interval = ${toString cfg.journalInterval}
    ${lib.optionalString (cfg.proxy != null) "proxy = ${cfg.proxy}"}

    host = ${
      if cfg.mpd.passwordFile != null
      then "{{MPD_PASSWORD}}@"
      else ""
    }${cfg.mpd.host}
    port = ${toString cfg.mpd.port}

    ${lib.concatStrings (lib.mapAttrsToList (name: ep: ''
        [${name}]
        url = ${ep.url}
        username = ${ep.username}
        password = {{${lib.toUpper name}_PASSWORD}}
        journal = ${xdgState}/mpdscribble/${name}.journal
      '')
      cfg.endpoints)}
  '';

  preStartScript = pkgs.writeShellScript "mpdscribble-pre-start" ''
    set -e
    CONF_TARGET="${xdgConfig}/mpdscribble/mpdscribble.conf"
    mkdir -p "$(dirname "$CONF_TARGET")"

    cp ${pkgs.writeText "mpdscribble-template" mkTemplate} "$CONF_TARGET"

    ${lib.optionalString (cfg.mpd.passwordFile != null) ''
      if [ -f "${cfg.mpd.passwordFile}" ]; then
        MPD_PASS="$(cat "${cfg.mpd.passwordFile}" | tr -d '\n')"
        sed -i "s/{{MPD_PASSWORD}}/$MPD_PASS/g" "$CONF_TARGET"
      else
        echo "Warning: MPD password file ${cfg.mpd.passwordFile} not found" >&2
      fi
    ''}

    ${lib.concatStrings (lib.mapAttrsToList (name: ep: ''
        if [ -f "${ep.passwordFile}" ]; then
          PASS="$(cat "${ep.passwordFile}" | tr -d '\n')"
          ESCAPED_PASS=$(printf '%s\n' "$PASS" | sed -e 's/[\/&]/\\&/g')
          sed -i "s/{{${lib.toUpper name}_PASSWORD}}/$ESCAPED_PASS/g" "$CONF_TARGET"
        else
          echo "Warning: password file for endpoint '${name}' not found at ${ep.passwordFile}" >&2
        fi
      '')
      cfg.endpoints)}
  '';
in {
  options.dotfiles.services.music.mpdscribble = {
    enable = lib.mkEnableOption "MPD scrobbler (Last.fm, ListenBrainz, etc.)";

    proxy = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "HTTP proxy URL.";
    };

    verbose = lib.mkOption {
      type = lib.types.int;
      default = 1;
      description = "Log verbosity (0=quiet, 1=normal, 2=debug).";
    };

    journalInterval = lib.mkOption {
      type = lib.types.int;
      default = 600;
      description = "Seconds between journal saves.";
    };

    mpd = {
      host = lib.mkOption {
        type = lib.types.str;
        default = "127.0.0.1";
        description = "MPD host (IP or hostname).";
      };
      port = lib.mkOption {
        type = lib.types.port;
        default = 6600;
        description = "MPD port.";
      };
      passwordFile = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = null;
        description = "File containing MPD password (if required).";
      };
    };

    endpoints = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule {
        options = {
          url = lib.mkOption {
            type = lib.types.str;
            description = "Scrobble endpoint URL.";
          };
          username = lib.mkOption {
            type = lib.types.str;
            description = "Username for the scrobble service.";
          };
          passwordFile = lib.mkOption {
            type = lib.types.path;
            description = "File containing the password (cleartext or MD5 hash).";
          };
        };
      });
      default = {};
      example = {
        "last.fm" = {
          url = "http://post.audioscrobbler.com";
          username = "myuser";
          passwordFile = "/home/me/.secrets/lastfm.pass";
        };
      };
      description = ''
        Scrobbling endpoints. If the endpoint name is one of ${lib.concatStringsSep ", " (lib.attrNames defaultUrls)},
        the URL is automatically set unless overridden.
      '';
    };
  };

  config = lib.mkIf (cfg.enable && mpdOn && servicesOn) {
    systemd.services.mpdscribble = {
      description = "MPD scrobbler daemon";
      wantedBy = ["default.target"];
      after = ["network.target" "mpd.service"];
      partOf = ["mpd.service"];

      serviceConfig = {
        Type = "simple";
        ExecStartPre = preStartScript;
        ExecStart = "${pkgs.mpdscribble}/bin/mpdscribble --no-daemon --conf ${xdgConfig}/mpdscribble/mpdscribble.conf";
        Restart = "on-failure";
        RestartSec = 5;
        RuntimeDirectory = "mpdscribble";
        StateDirectory = "mpdscribble";
        ExecStopPost = "${pkgs.coreutils}/bin/rm -f ${xdgConfig}/mpdscribble/mpdscribble.conf";
      };
    };
  };
}
